version: '3'
services:
  frontend:
    container_name: frontend
    image:
      cr.yandex/crpp057q4ht1sd0rvi6v/frontendperm:latest
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    image:
      cr.yandex/crpp057q4ht1sd0rvi6v/backendperm:latest
    ports:
      - 8000:8000
    restart: always